name: Deploy to GitHub pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  lint_format:
    name: Run le linter et formatteur
    runs-on: ubuntu-latest
    steps:
      - run: npm run build
      - run: npm run test:e2e

  tests:
    name: Run les tests
    runs-on: ubuntu-latest
    steps:
      - run: npm run test:e2e:dev
      - run: npm run lint
  
  build_prod:
    name: Build le dossier de prod
    runs-on: ubuntu-latest
    steps:
      - run: npm run build