name: Deploy to GitHub pages

on:
  push:
    branches:
      - main
  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
      - name: Installation des dépendances
        run: npm ci

  linter_et_formatteur:
    name: Run le linter et formatteur
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run du linter
        run: npm run lint
      - name: Run le formateur
        run: npm run format

  test:
    name: Run les tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
      - name: Installation des dépendances
        run: npm ci
      - name: Execution des tests
        run: npm run test

  build_prod:
    name: Build du dossier de prod
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
      - name: Installation des dépendances
        run: npm ci
      - run: npm run build

  # test_e2e:
  #   name: Recupère le dossier dist et lance les test e2e
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Setup node
  #       uses: actions/setup-node@v4
  #     - name: Installation des dépendances
  #       run: npm ci
  #     - name: Lance les test e2e
  #       run: npm run test:e2e:dev

  deploy:
    name: Deploie les sources sur Github Action
    needs: [linter_et_formatteur, build_prod]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
      - name: Build
        run: npm run build
      - name: Deploy
        uses: actions/deploy-pages@v4
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist